### ISSUE TITLE
[Refactor] Build-logic 리팩토링, init network-module 

### ISSUE THREAD

**Issue by murjune** [Nexters/Funch-AOS#20]
## ISSUE
- 네트워크 통신 모듈 만들기
- Build-logic 구조 다시 짜기..

## To-Do
- [x] kapt -> ksp 마이그레이션
- [x] configureAndroidCommonPlugin 함수 리팩토링
- [x] Application, Library -> Application, Feature, Library 형태로 리팩토링
