### ISSUE TITLE
[Feat] 프로필 생성 UI 제작

### ISSUE THREAD

**Issue by ham2174** [Nexters/Funch-AOS#50]
## ISSUE
- 프로필 생성 UI 제작
<img src="https://github.com/Nexters/Funch-AOS/assets/54674781/a731fe0b-6cfb-4b74-bc24-2e2fa65bae5b" width=160 height=340>

## To-Do
- [ ] : 프로필 생성 UI 제작

**Comment by ham2174** [comment]
### 💥UI 이슈
- [ ] : FunchTextField에서 '홓' 이라고 입력시 innerTextFiled의 높이가 올라가 innerTextField가 움직이는 현상

- [ ] : 혈액형 드롭다운 메뉴 화면 스크롤시 움직이는 현상

- [ ] : 혈액형 드롭다운 메뉴가 '매칭할래요' 버튼보다 z축이 상단에 있는 현상

- [x] : 지하철 포커스시 상단 탑바 없어지는 현상
  - 화면의 레이아웃을 Scaffold 사용하는것으로 해결

### 추가 TO-DO
- [ ] : MBTI 입력시 뷰모델에서 Mbti enum class로 값 변환해서 넣기
- [ ] : 지하철 검색시 하단 리스트 넣기
- [ ] : 모든 값을 입력했을 때 버튼 활성화 상태로 만들기
- [ ] : 혈액형 드롭다운 메뉴 다른곳 터치시 메뉴 collapsed 상태로 만들기
