### ISSUE TITLE
[Feat] Profile

### ISSUE THREAD

**Issue by ham2174** [Nexters/Funch-AOS#8]
## To-Do
- [x] : home 모듈 생성
- [x] : profile 모듈 생성
- [x] : 홈 UI 제작
- [x] : Navigation 셋팅 및 프로필생성 - 홈 - 내프로필 연결
- [ ] : 내 프로필 UI 제작
- [ ] : ~~피드백 보내기 구글폼 연결~~
- [ ] : ~~친구 코드 입력 후 Matching Screen Navigation 연결~~ (준원이 피처에서 개발)
- [x] : MyProfile Screen Navigation 연결
- [ ] : 내 정보 `GET` 호출
- [ ] : 내 정보 `EncryptedSharedPreferences`로 저장
